[package]
name = "sigop-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.1"
regex = "1.5.6"
indicatif = "0.16.2"

[dev-dependencies]
hex = "0.4.3"